import { useEffect, useRef, useState } from 'react'
import * as THREE from 'three'
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'
import type { FinalizedDenseRealityReconstruction } from '../types'
import { auditRealitySurfaceScreenSpace, auditRealityTriangleScreenSpace, restoreRealitySurface, type PreparedRealitySurface, type RealityScreenSpaceCoverageDiagnostics, type RealitySurfaceRenderResources } from '../services/realitySurfaceRenderingService'
import type { RealityRefinementStats } from '../services/realityDisplayRefinement'
import type { RealityConfidenceFilterStats } from '../services/realityConfidenceFiltering'
import M812SynchronizedRgbdProofPreview from './M812SynchronizedRgbdProofPreview'
import M813ViewDependentVisualRealityPreview from './M813ViewDependentVisualRealityPreview'
import ScanCaptureDownload from './ScanCaptureDownload'

const modes = [['raw-accepted', '1. Raw Accepted Measurement Audit'], ['live', '2. Live Lightweight Fusion'], ['retained', '3. Per-Frame Consolidated Measurements'], ['canonical', '4. Post-Scan Canonical Fusion'], ['baseline-canonical', 'M8.7.1.6 Baseline Canonical'], ['baseline-flat-triangles', 'M8.7.1.6 Flat Triangle Control'], ['confidence', '5. Confidence Filtered Canonical'], ['hybrid', '6. Canonical Hybrid Mesh + Surfels'], ['base-color', '7. Base Real RGB Canonical'], ['high-res', '8. High-Res Color Refined'], ['final', '9. Final M8.7.1.6 Reality'], ['textured', '10. Textured Canonical Reality'], ['provisional-expiry', 'Provisional Outcomes Map (diagnostic)'], ['canonical-triangulated', 'Triangulation Only (diagnostic)'], ['layers', 'Depth Layers — 10 cm range bands'], ['discontinuities', 'Depth Discontinuities'], ['new', 'New Geometry — first observed time'], ['views', 'Multi-View Observation Count'], ['reveal', 'Recess / Occlusion Reveal'], ['trajectory', 'Scan Trajectory']]
export default function RealityQualityPreview({ source, replayMode = false, replayDescription }: { source: FinalizedDenseRealityReconstruction; replayMode?: boolean; replayDescription?: string }) {
  const host = useRef<HTMLDivElement>(null), worker = useRef<Worker | null>(null), requestId = useRef(0)
  const [mode, setMode] = useState('final'), [busy, setBusy] = useState(true), [error, setError] = useState('')
  const [showExperiments, setShowExperiments] = useState(false)
  const [result, setResult] = useState<{ prepared: PreparedRealitySurface; stats: RealityRefinementStats; filterStats: RealityConfidenceFilterStats } | null>(null)
  const [screenSpaceAudit, setScreenSpaceAudit] = useState<RealityScreenSpaceCoverageDiagnostics | null>(null)
  const [renderInfo, setRenderInfo] = useState({ width: 0, height: 0, dpr: 1, fps: 0, drawCalls: 0, restoreSetupMs: null as number | null, firstRenderCallMs: null as number | null, rollingRenderCallMs: null as number | null })
  const [previewTiming, setPreviewTiming] = useState<{ mountEpochMs: number | null; firstRestoredSurfacePaintEpochMs: number | null; mountToFirstPaintMs: number | null; finishToMountMs: number | null; finishToFirstPaintMs: number | null; finishStartToMountMs: number | null; finishStartToFirstPaintMs: number | null }>({ mountEpochMs: null, firstRestoredSurfacePaintEpochMs: null, mountToFirstPaintMs: null, finishToMountMs: null, finishToFirstPaintMs: null, finishStartToMountMs: null, finishStartToFirstPaintMs: null })
  const currentMode = useRef(mode)
  useEffect(() => {
    if (!host.current) return
    const container = host.current
    const previewMountEpochMs = typeof performance === 'undefined' ? Date.now() : performance.timeOrigin + performance.now()
    const finishDiagnostics = source.finishPipelineDiagnostics
    setPreviewTiming({ mountEpochMs: previewMountEpochMs, firstRestoredSurfacePaintEpochMs: null, mountToFirstPaintMs: null, finishToMountMs: finishDiagnostics ? previewMountEpochMs - finishDiagnostics.finishCompletedEpochMs : null, finishToFirstPaintMs: null, finishStartToMountMs: finishDiagnostics ? previewMountEpochMs - finishDiagnostics.finishStartedEpochMs : null, finishStartToFirstPaintMs: null })
    let renderer: THREE.WebGLRenderer
    try { renderer = new THREE.WebGLRenderer({ antialias: true }) } catch {
      let cancelled = false
      queueMicrotask(() => { if (!cancelled) { setBusy(false); setError('Quality preview graphics unavailable. Open the frozen preview or retry on a supported device.') } })
      return () => { cancelled = true }
    }
    renderer.outputColorSpace = THREE.SRGBColorSpace; renderer.setPixelRatio(Math.min(2, window.devicePixelRatio || 1)); container.append(renderer.domElement)
    const scene = new THREE.Scene(); scene.background = new THREE.Color('#111b24')
    const trailGeometry = new THREE.BufferGeometry().setFromPoints((source.qualityTelemetry?.trajectory ?? []).map((p) => new THREE.Vector3(p.position.x, p.position.y, p.position.z)))
    const trail = new THREE.Line(trailGeometry, new THREE.LineBasicMaterial({ color: '#ffcc33' })); scene.add(trail); trail.visible = false
    const camera = new THREE.PerspectiveCamera(60, 1, .04, 80)
    const controls = new OrbitControls(camera, renderer.domElement); controls.enableDamping = true
    const bounds = new THREE.Box3(); (source.canonicalSurfels ?? source.surfels).forEach((s) => bounds.expandByPoint(new THREE.Vector3(s.position.x, s.position.y, s.position.z)))
    const center = bounds.isEmpty() ? new THREE.Vector3() : bounds.getCenter(new THREE.Vector3()), extent = bounds.isEmpty() ? 2 : Math.max(1, bounds.getSize(new THREE.Vector3()).length())
    camera.position.copy(center).add(new THREE.Vector3(extent * .3, extent * .15, extent * .7)); controls.target.copy(center); controls.update()
    const resize = () => { const w = container.clientWidth, h = container.clientHeight; renderer.setSize(w, h); camera.aspect = w / Math.max(1, h); camera.updateProjectionMatrix() }
    const observer = new ResizeObserver(resize); observer.observe(container); resize()
    let resources: RealitySurfaceRenderResources | null = null, raf = 0, frames = 0, lastReport = performance.now(), slowReports = 0, firstRestoredSurfacePaintRecorded = false
    let pendingFirstRender = false, restoreSetupMs: number | null = null, firstRenderCallMs: number | null = null, rollingRenderCallMs: number | null = null
    const renderCallSamples: number[] = []
    const disposeResources = () => { if (!resources) return; scene.remove(resources.group); resources.geometries.forEach((g) => g.dispose()); resources.materials.forEach((m) => { if (m instanceof THREE.MeshBasicMaterial) m.map?.dispose(); m.dispose() }); resources = null }
    const preparation = new Worker(new URL('../services/realityQuality.worker.ts', import.meta.url), { type: 'module' }); worker.current = preparation
    const id = ++requestId.current
    const expiryMap = source.provisionalExpiryMap ?? source.canonicalFusionDiagnostics?.provisionalExpiryMap
    const consolidatedMap = source.consolidatedMeasurementMap
    // Keep the finalized snapshot readable on the main thread while giving the
    // preview worker ownership of an explicit bounded packed copy.
    const workerExpiryMap = expiryMap && Object.freeze({ ...expiryMap, positions: expiryMap.positions.slice(), reasonCodes: expiryMap.reasonCodes.slice() })
    const workerConsolidatedMap = consolidatedMap && Object.freeze({ ...consolidatedMap, positions: consolidatedMap.positions.slice() })
    const { m810DepthKeyframePatchAtlas: _m810Atlas, m812SynchronizedRgbd: _m812Snapshot, retainedMeasurements: _replayInput, ...sourceForWorker } = source
    // The quality worker does not consume the large experimental RGB-D snapshot.
    // It remains on the main thread for an explicit lazy M8.13 build.
    const workerSource = workerExpiryMap || workerConsolidatedMap ? Object.freeze({ ...sourceForWorker,
      provisionalExpiryMap: workerExpiryMap ?? source.provisionalExpiryMap,
      consolidatedMeasurementMap: workerConsolidatedMap ?? source.consolidatedMeasurementMap,
      canonicalFusionDiagnostics: source.canonicalFusionDiagnostics && Object.freeze({ ...source.canonicalFusionDiagnostics, provisionalExpiryMap: workerExpiryMap ?? source.canonicalFusionDiagnostics.provisionalExpiryMap }),
    }) : sourceForWorker
    const transfers = [
      ...(workerExpiryMap ? [workerExpiryMap.positions.buffer, workerExpiryMap.reasonCodes.buffer] : []),
      ...(workerConsolidatedMap ? [workerConsolidatedMap.positions.buffer] : []),
    ]
    preparation.postMessage({ source: workerSource, mode: currentMode.current, id }, transfers)
    preparation.onmessage = (event: MessageEvent<{ id: number; error?: string; prepared: PreparedRealitySurface; stats: RealityRefinementStats; filterStats: RealityConfidenceFilterStats }>) => {
      if (event.data.id !== requestId.current) return
      setBusy(false)
      if (event.data.error) { setScreenSpaceAudit(null); setError(event.data.error); return }
      const restoreStartedAt = performance.now()
      disposeResources(); resources = restoreRealitySurface(event.data.prepared); scene.add(resources.group)
      restoreSetupMs = Math.max(0, performance.now() - restoreStartedAt)
      firstRenderCallMs = null
      rollingRenderCallMs = null
      renderCallSamples.length = 0
      pendingFirstRender = true
      setRenderInfo((previous) => ({ ...previous, restoreSetupMs, firstRenderCallMs: null, rollingRenderCallMs: null }))
      setResult(event.data)
      const triangleAuditMode = currentMode.current === 'baseline-flat-triangles'
      const comparisonSurfels = currentMode.current === 'baseline-canonical' ? (source.canonicalSurfels ?? source.surfels) : null
      setScreenSpaceAudit(triangleAuditMode && resources.triangleGeometry
        ? auditRealityTriangleScreenSpace(resources.triangleGeometry, camera, renderer.domElement.width, renderer.domElement.height)
        : comparisonSurfels ? auditRealitySurfaceScreenSpace(comparisonSurfels, camera, renderer.domElement.width, renderer.domElement.height) : null)
    }
    preparation.onerror = () => { setBusy(false); setError('Quality worker failed. Original Reality remains available below.') }
    const render = (time: number) => {
      raf = requestAnimationFrame(render); controls.update(); trail.visible = currentMode.current === 'trajectory'
      const renderStartedAt = performance.now()
      renderer.render(scene, camera)
      const renderCallMs = Math.max(0, performance.now() - renderStartedAt)
      renderCallSamples.push(renderCallMs)
      if (renderCallSamples.length > 60) renderCallSamples.shift()
      rollingRenderCallMs = renderCallSamples.reduce((sum, sample) => sum + sample, 0) / Math.max(1, renderCallSamples.length)
      if (pendingFirstRender) {
        pendingFirstRender = false
        firstRenderCallMs = renderCallMs
      }
      frames++
      if (resources && !firstRestoredSurfacePaintRecorded) {
        firstRestoredSurfacePaintRecorded = true
        const firstRestoredSurfacePaintEpochMs = typeof performance === 'undefined' ? Date.now() : performance.timeOrigin + performance.now()
        setPreviewTiming({ mountEpochMs: previewMountEpochMs, firstRestoredSurfacePaintEpochMs, mountToFirstPaintMs: firstRestoredSurfacePaintEpochMs - previewMountEpochMs, finishToMountMs: finishDiagnostics ? previewMountEpochMs - finishDiagnostics.finishCompletedEpochMs : null, finishToFirstPaintMs: finishDiagnostics ? firstRestoredSurfacePaintEpochMs - finishDiagnostics.finishCompletedEpochMs : null, finishStartToMountMs: finishDiagnostics ? previewMountEpochMs - finishDiagnostics.finishStartedEpochMs : null, finishStartToFirstPaintMs: finishDiagnostics ? firstRestoredSurfacePaintEpochMs - finishDiagnostics.finishStartedEpochMs : null })
      }
      if (time - lastReport > 1500) {
        const fps = frames * 1000 / (time - lastReport)
        slowReports = fps < 32 ? slowReports + 1 : 0
        if (slowReports >= 2 && renderer.getPixelRatio() > 1) { renderer.setPixelRatio(Math.max(1, renderer.getPixelRatio() - .25)); resize(); slowReports = 0 }
        setRenderInfo({ width: renderer.domElement.width, height: renderer.domElement.height, dpr: renderer.getPixelRatio(), fps: Math.round(fps), drawCalls: renderer.info.render.calls, restoreSetupMs, firstRenderCallMs, rollingRenderCallMs })
        frames = 0; lastReport = time
      }
    }; raf = requestAnimationFrame(render)
    return () => { worker.current = null; preparation.terminate(); cancelAnimationFrame(raf); observer.disconnect(); controls.dispose(); disposeResources(); trailGeometry.dispose(); trail.material.dispose(); renderer.dispose(); renderer.forceContextLoss(); renderer.domElement.remove() }
  }, [source])
  const select = (value: string) => {
    setMode(value); currentMode.current = value; setScreenSpaceAudit(null); setBusy(true); setError('')
    const id = ++requestId.current
    worker.current?.postMessage({ mode: value, id })
  }
  const stats = result?.stats, filter = result?.filterStats, q = source.qualityTelemetry, fusion = source.fusionDiagnostics, appearance = source.appearanceKeyframes?.diagnostics, measurement = source.measurementDiagnostics, queue = source.measurementQueueDiagnostics, retained = source.retainedMeasurementDiagnostics, canonical = source.canonicalFusionDiagnostics, finish = source.finishPipelineDiagnostics
  const appearanceSource = source.appearanceKeyframes?.keyframes.at(-1)?.mapping
  const texture = result?.prepared.textureStats
  const lowestTextureRegions = texture?.spatialRegionCoverage.slice().sort((a, b) => a.percentage - b.percentage || b.totalTriangles - a.totalTriangles).slice(0, 6) ?? []
  const availableModes = replayMode
    ? modes.filter(([value]) => ['canonical', 'baseline-canonical', 'baseline-flat-triangles', 'confidence', 'hybrid', 'base-color', 'high-res', 'final', 'textured'].includes(value) || (value === 'retained' && Boolean(source.consolidatedMeasurementMap)))
    : modes
  const lowQuality = Boolean(filter && (filter.repeatability.stableSampleRatio < .3 || filter.floatingComponentsRejected > Math.max(4,filter.connectedComponentCount*.35)) || measurement && measurement.accepted < Math.max(3,measurement.ticksConsidered*.35))
  return <section aria-label="Captured room model" style={{ marginBlock: 24 }}>
    <h2>Your captured room</h2>
    <p>Drag to look around; pinch to zoom. Check the model from several sides. Missing measurements and reconstruction errors can both leave gaps.</p>
    <p>Walls remain measured surfaces. Object sides and recesses keep their recorded depth. Hidden surfaces and exact dimensions are not verified by this preview.</p>
    {replayMode && <p>{replayDescription ?? 'This preview was rebuilt locally from the saved measurements. Live scan coverage history is not included in the capture file.'}</p>}
    {lowQuality && <p role="alert">This capture has limited reliable geometry. Missing or distorted surfaces may remain in the preview.</p>}
    {!replayMode && <ScanCaptureDownload key={source.scanId} source={source} />}
    <details><summary>Compare reconstruction stages</summary>
    <label>Quality comparison <select value={mode} onChange={(e) => select(e.target.value)}>{availableModes.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
    {mode === 'layers' && <p>Range bands from the first recorded scanner position, not inferred planar layers.</p>}
    {mode === 'reveal' && <p>First-observed time: green/blue is earlier, magenta is later. This shows when geometry was revealed; it does not label a recess semantically.</p>}
    {mode === 'views' && <p>Orange: one angular view bin. Green: multiple bins. Repeat ticks alone do not establish viewpoint diversity.</p>}
    {mode === 'raw-accepted' && <p>Bounded audit samples from measurements that passed the immutable frame gate. This is not the retained replay input.</p>}
    {mode === 'live' && <p>Bounded, decimated live fusion used only for guidance and map inspection. It is not the source of Final Reality.</p>}
    {mode === 'retained' && <p>Bounded, one-actual-measurement-per-cell samples from the per-frame-consolidated input used by deterministic canonical replay.</p>}
    {mode === 'canonical' && <p>Deterministic post-scan replay after per-frame consolidation, robust surfel updates and provisional-layer resolution.</p>}
    {mode === 'baseline-canonical' && <p>Current production canonical geometry from this retained capture, before appearance refinement.</p>}
    {mode === 'baseline-flat-triangles' && <p>Flat triangle control: current canonical geometry with one diagnostic color.</p>}
    {mode === 'provisional-expiry' && <p>Measured canonical outcomes. Green: promoted; orange: temporal support; magenta: multi-view; cyan: replaced; red: duplicate parallel layer; gray: isolated/noisy; yellow: capacity/layer policy; white: other. This bounded map does not fill geometry.</p>}
    {mode === 'confidence' && <p>Final safety filtering over canonical—not live—geometry. Supported recesses and protrusions remain measured.</p>}
    {mode === 'hybrid' && <p>Every oriented canonical measured disc remains as a depth-biased coverage underlay beneath the safe measured triangle skin.</p>}
    {mode === 'base-color' && <p>Real registered RGB retained with accepted reconstruction measurements; no high-resolution keyframe refinement.</p>}
    {mode === 'high-res' && <p>Optional visibility-aware high-resolution RGB refinement applied over the real registered RGB baseline.</p>}
    {mode === 'textured' && <p>Each existing triangle chooses the best real keyframe shared by all three vertices’ bounded visibility-approved view sets. Every other triangle and splat keeps base per-surfel RGB.</p>}
    </details>
    {busy && <p role="status">Preparing measured display geometry in worker…</p>}{error && <p role="alert">{error}</p>}
    <div ref={host} style={{ height: 440, maxHeight: '65vh', width: '100%', touchAction: 'none', borderRadius: 12, overflow: 'hidden' }} />
    {source.m812SynchronizedRgbd?.status === 'available' && <details onToggle={(event) => setShowExperiments(event.currentTarget.open)}>
      <summary>Experimental comparisons</summary>
    {showExperiments && <M813ViewDependentVisualRealityPreview
      snapshot={source.m812SynchronizedRgbd}
      baselineSurfels={source.canonicalSurfels ?? source.surfels}
    />}
    {showExperiments && <M812SynchronizedRgbdProofPreview snapshot={source.m812SynchronizedRgbd} />}
    </details>}
    {!replayMode && <details><summary>Frame acceptance, stability, components and repeatability</summary>
    {canonical?.visibility && <p>Measured visibility: checked {canonical.visibility.checkedFrames} calibrated views; removed {canonical.visibility.removedSamples} samples contradicted by clear-space measurements. Preserved nearer-object occlusions in {canonical.visibility.occludedComparisons} comparisons.</p>}
      <p>Measurement funnel: candidate ticks {measurement?.candidateTicks ?? 0}; cadence skipped {measurement?.cadenceSkipped ?? 0}; stationary skipped {measurement?.skippedTogether ?? 0}; backpressure skipped {measurement?.backpressureSkipped ?? 0}; considered {measurement?.ticksConsidered ?? 0}; accepted {measurement?.accepted ?? 0}; fused {measurement?.fusedSuccessfully ?? 0}. Acceptance {measurement?.acceptedPercentage.toFixed(1) ?? 0}%; fused {measurement?.fusedPercentage.toFixed(1) ?? 0}%.</p>
      <p>Rejected: motion {measurement?.motionRejected ?? 0}; tracking {measurement?.trackingRejected ?? 0}; depth {measurement?.depthRejected ?? 0}; pose discontinuity {measurement?.poseDiscontinuityRejected ?? 0}; world consistency {measurement?.consistencyRejected ?? 0}. Depth reasons: missing {measurement?.depthRejectedMissing ?? 0}; valid ratio {measurement?.depthRejectedValidRatio ?? 0}; sample count {measurement?.depthRejectedSampleCount ?? 0}; outliers {measurement?.depthRejectedOutliers ?? 0}; discontinuity {measurement?.depthRejectedDiscontinuity ?? 0}; range {measurement?.depthRejectedRange ?? 0}.</p>
      <p>Spatial validity: {measurement?.scanSpatialValidity ?? 'unknown'} ({measurement?.scanSpatialValidityReason ?? 'none'}); reference-space resets {measurement?.referenceSpaceResetCount ?? 0}; pose epochs observed/accepted {measurement?.poseEpochCount ?? 0}/{measurement?.acceptedPoseEpochCount ?? 0}. Finish gate requires one healthy epoch.</p>
      {queue && <><p>Latest-only queue: depth {queue.queueDepth}/{queue.maximumQueueDepth}; completed {queue.completedPackets}; replaced {queue.packetsReplaced}; dropped {queue.packetsDropped}; failed {queue.failedPackets}. Packet latency p50/p95/max {queue.latencyP50Ms.toFixed(1)} / {queue.latencyP95Ms.toFixed(1)} / {queue.latencyMaxMs.toFixed(1)} ms; processing {queue.processingP50Ms.toFixed(1)} / {queue.processingP95Ms.toFixed(1)} / {queue.processingMaxMs.toFixed(1)} ms.</p>
        <p>Capture p50/p95/max: depth {queue.stageTimings['depth-capture'].p50Ms.toFixed(1)} / {queue.stageTimings['depth-capture'].p95Ms.toFixed(1)} / {queue.stageTimings['depth-capture'].maxMs.toFixed(1)} ms; reconstruction {queue.stageTimings['world-reconstruction'].p50Ms.toFixed(1)} / {queue.stageTimings['world-reconstruction'].p95Ms.toFixed(1)} / {queue.stageTimings['world-reconstruction'].maxMs.toFixed(1)} ms; validation {queue.stageTimings['packet-validation'].p50Ms.toFixed(1)} / {queue.stageTimings['packet-validation'].p95Ms.toFixed(1)} / {queue.stageTimings['packet-validation'].maxMs.toFixed(1)} ms; RGB registration {queue.stageTimings['rgb-registration'].p50Ms.toFixed(1)} / {queue.stageTimings['rgb-registration'].p95Ms.toFixed(1)} / {queue.stageTimings['rgb-registration'].maxMs.toFixed(1)} ms; appearance {queue.stageTimings['appearance-copy'].p50Ms.toFixed(1)} / {queue.stageTimings['appearance-copy'].p95Ms.toFixed(1)} / {queue.stageTimings['appearance-copy'].maxMs.toFixed(1)} ms.</p>
        <p>Deferred p50/p95/max: coverage {queue.stageTimings.coverage.p50Ms.toFixed(1)} / {queue.stageTimings.coverage.p95Ms.toFixed(1)} / {queue.stageTimings.coverage.maxMs.toFixed(1)} ms; persistent surface {queue.stageTimings['persistent-surface'].p50Ms.toFixed(1)} / {queue.stageTimings['persistent-surface'].p95Ms.toFixed(1)} / {queue.stageTimings['persistent-surface'].maxMs.toFixed(1)} ms; Dense fusion {queue.stageTimings['dense-fusion'].p50Ms.toFixed(1)} / {queue.stageTimings['dense-fusion'].p95Ms.toFixed(1)} / {queue.stageTimings['dense-fusion'].maxMs.toFixed(1)} ms; render prep {queue.stageTimings['render-preparation'].p50Ms.toFixed(1)} / {queue.stageTimings['render-preparation'].p95Ms.toFixed(1)} / {queue.stageTimings['render-preparation'].maxMs.toFixed(1)} ms.</p></>}
      <p>Translation p50/p90/p95/max {measurement?.translationP50Meters.toFixed(3) ?? '?'} / {measurement?.translationP90Meters.toFixed(3) ?? '?'} / {measurement?.translationP95Meters.toFixed(3) ?? '?'} / {measurement?.largestTranslationMeters.toFixed(2) ?? '?'} m; rotation p50/p90/p95/max {measurement?.rotationP50Degrees.toFixed(1) ?? '?'} / {measurement?.rotationP90Degrees.toFixed(1) ?? '?'} / {measurement?.rotationP95Degrees.toFixed(1) ?? '?'} / {measurement?.largestRotationDegrees.toFixed(1) ?? '?'}°. Relocalization-like events {measurement?.relocalizationLikeEvents ?? 0}.</p>
      <p>Last depth valid {((measurement?.validRatio ?? 0)*100).toFixed(1)}%; outliers {((measurement?.outlierRatio ?? 0)*100).toFixed(1)}%; median/p95 {measurement?.medianDepthMeters.toFixed(2) ?? '?'} / {measurement?.p95DepthMeters.toFixed(2) ?? '?'} m; validation {measurement?.validationMs.toFixed(2) ?? '?'} ms.</p>
      {retained && <p>Retained reconstruction measurements: {retained.framesRetained}/{retained.framesConsidered} frames; {retained.samplesRetained} samples; tracking epochs {retained.trackingEpochCount} [{retained.trackingEpochIds.join(', ')}]; incompatible-state rejects {retained.incompatibleTrackingStateRejects}; viewpoint bins {retained.viewpointBinCount}; redundancy rejects {retained.redundancyRejects}; coverage-aware replacements {retained.compactionReplacements}; proxy cells lost by removal {retained.coverageLostDueToRemoval}; base RGB evidence {retained.retainedColorEvidenceCount} samples across {retained.retainedColorFrameCount} frames; {(retained.memoryBytes / 1048576).toFixed(2)} MiB.</p>}
      {canonical && <><p>Canonical replay: {canonical.inputObservations} input → {canonical.consolidatedObservations} consolidated observations → {canonical.canonicalSurfels} surfels ({canonical.observationsPerCanonicalSurfel.toFixed(2)} observations/surfel). Per-frame redundant samples removed {canonical.sameFrameConsolidated}; worker {canonical.workerTimeMs.toFixed(1)} ms.</p>
        <p>Lifecycle: provisional created {canonical.provisionalCreated}; promoted {canonical.provisionalPromoted} ({canonical.surfaceCoherentPromotions} surface-coherent); expired {canonical.provisionalExpired}; weak recycled {canonical.weakProvisionalsRecycled}; canonical reinforcements {canonical.canonicalMerges}; false parallel layers collapsed {canonical.falseParallelLayersCollapsed}; unresolved removed {canonical.unresolvedParallelLayers}; true separate layers retained {canonical.trueSeparateLayersRetained}; outliers rejected {canonical.outliersRejected}; global/local capacity rejects {canonical.globalCapacityRejected}/{canonical.localLayerCapacityRejected}.</p>
        <p>Point-to-plane thickness proxy p50/p90/p95 {(canonical.wallThicknessP50Meters * 1000).toFixed(1)} / {(canonical.wallThicknessP90Meters * 1000).toFixed(1)} / {(canonical.wallThicknessP95Meters * 1000).toFixed(1)} mm. Dominant locally planar ({canonical.dominantPlanarSurfelCount}) p50/p90/p95 {(canonical.dominantPlanarThicknessP50Meters * 1000).toFixed(1)} / {(canonical.dominantPlanarThicknessP90Meters * 1000).toFixed(1)} / {(canonical.dominantPlanarThicknessP95Meters * 1000).toFixed(1)} mm. Transitions existing canonical/provisional/new/parallel/true-layer/outlier: {canonical.transitionExistingCanonical}/{canonical.transitionExistingProvisional}/{canonical.transitionNewCoherent}/{canonical.transitionPossibleParallelDuplicate}/{canonical.transitionTrueSeparatedLayer}/{canonical.transitionOutlier}.</p>
        <p>Base real RGB: {canonical.baseColorInputObservations} retained observations → {canonical.baseColorConsolidatedObservations} consolidated → {canonical.baseColorCanonicalSurfels}/{canonical.canonicalSurfels} canonical surfels ({canonical.baseColorCoveragePercentage.toFixed(1)}%). Expiry reasons temporal/multi-view/replaced/isolated/parallel/capacity/other: {canonical.expiryReasons.insufficientTemporalSupport}/{canonical.expiryReasons.insufficientMultiViewSupport}/{canonical.expiryReasons.replacedByCanonical}/{canonical.expiryReasons.isolatedOrNoisy}/{canonical.expiryReasons.duplicateParallelLayer}/{canonical.expiryReasons.capacityOrLayerPolicy}/{canonical.expiryReasons.other}. Map sampled {canonical.provisionalExpiryMap.sampled}/{canonical.provisionalExpiryMap.total} (omitted {canonical.provisionalExpiryMap.omitted}; cap {canonical.provisionalExpiryMap.capacity}).</p>
        <p>Completeness funnel: {canonical.completenessStages.map((stage) => `${stage.name} ${stage.count} (${stage.percentageOfPrior.toFixed(1)}% prior; ${stage.spatialCoverageCells} cells; ${stage.surfaceAreaProxySquareMeters.toFixed(2)} m² proxy)`).join(' → ')}. Provisional count is cumulative admission events; its cells are unique cells admitted as new. Canonical/consolidated spatial coverage {canonical.canonicalCoverageOfConsolidatedPercentage.toFixed(1)}%.</p>
        <p>Coverage transition: {canonical.coverageTransition.consolidatedCells} consolidated cells; {canonical.coverageTransition.matchedObservationEvents} matched observation events; {canonical.coverageTransition.cellsAdmittedAsNew} cells admitted-new; {canonical.coverageTransition.cellsRejectedAsOutliers} cells rejected as outliers; {canonical.coverageTransition.cellsRejectedByCapacity} cells rejected by capacity/layer policy; {canonical.coverageTransition.finalCanonicalCells} final cells. Cell outcome sets can overlap when revisited. Stage-3 map sampled {source.consolidatedMeasurementMap?.sampled ?? 0}/{source.consolidatedMeasurementMap?.total ?? 0} cells.</p>
        <p>Promotion audit: standard/coherent {canonical.promotionAudit.standardPromotions}/{canonical.promotionAudit.surfaceCoherentPromotions}; expired below 3 frames/short span/no neighbors {canonical.promotionAudit.expiredBelowThreeFrames}/{canonical.promotionAudit.expiredShortCaptureSpan}/{canonical.promotionAudit.expiredWithoutCanonicalNeighbors}; max retained/original sequence spans {canonical.promotionAudit.maximumRetainedSequenceSpan}/{canonical.promotionAudit.maximumOriginalFrameSpan}; max baseline {canonical.promotionAudit.maximumViewpointBaselineMeters.toFixed(2)} m.</p>
        <p>Worker stages ms: input {canonical.workerStageTimingsMs.unpackInput.toFixed(1)}; consolidation {canonical.workerStageTimingsMs.perFrameConsolidation.toFixed(1)}; replay matching {canonical.workerStageTimingsMs.replayMatching.toFixed(1)}; promotion/cleaning {canonical.workerStageTimingsMs.promotionAndCleaning.toFixed(1)}; parallel collapse {canonical.workerStageTimingsMs.parallelCollapse.toFixed(1)}; final packing {canonical.workerStageTimingsMs.finalPacking.toFixed(1)}. Exact-match grid probes {canonical.matchingBucketProbes}; candidate visits {canonical.matchingCandidateVisits}.</p></>}
      {screenSpaceAudit && (mode === 'baseline-canonical' || mode === 'baseline-flat-triangles') && <p>Screen-space A/B audit (deterministic downsample {screenSpaceAudit.rasterWidth} × {screenSpaceAudit.rasterHeight}): primitives {screenSpaceAudit.inputPrimitiveCount}; frustum rejects {screenSpaceAudit.frustumRejectedPrimitiveCount}; in-frustum/visible/depth-hidden {screenSpaceAudit.inFrustumPrimitiveCount}/{screenSpaceAudit.visiblePrimitiveCount}/{screenSpaceAudit.depthHiddenPrimitiveCount}; useful pixels {screenSpaceAudit.usefulPixelCount}; holes {(screenSpaceAudit.holeFraction * 100).toFixed(1)}%; overlap tests/pixel {screenSpaceAudit.overlapTestsPerUsefulPixel.toFixed(2)}; depth competitions &gt;22/&gt;50 mm {screenSpaceAudit.depthCompetitionOver22mm ?? 0}/{screenSpaceAudit.depthCompetitionOver50mm ?? 0}; boundary pixels {screenSpaceAudit.boundaryPixelCount ?? 0}. This is a camera/raster diagnostic, not a physical major-surface measurement.</p>}
      {finish && <><p>Finish pipeline: click→processing paint {finish.clickToProcessingUiFirstPaintMs.toFixed(1)} ms; click→finalization {finish.clickToRetainedFinalizationBeginMs.toFixed(1)} ms; click→worker post {finish.clickToWorkerMessagePostedMs.toFixed(1)} ms; drain {finish.stopAndCaptureDrainMs.toFixed(1)} ms; retained finalization {finish.retainedMeasurementFinalizationMs.toFixed(1)} ms; canonical worker round trip {finish.canonicalWorkerRoundTripMs.toFixed(1)} ms (worker compute {finish.canonicalWorkerMs.toFixed(1)} ms); result assembly {finish.resultAssemblyMs.toFixed(1)} ms; XR end {finish.xrSessionEndMs.toFixed(1)} ms; total {finish.totalFinishMs.toFixed(1)} ms. Preview timing is measured locally below without mutating the frozen result.</p>
        <p>Finish snapshots ms: live surface {finish.snapshotStageTimingsMs.liveSurface.toFixed(1)}; spatial scan {finish.snapshotStageTimingsMs.spatialScan.toFixed(1)}; base Reality {finish.snapshotStageTimingsMs.baseReality.toFixed(1)}; dense Reality {finish.snapshotStageTimingsMs.denseReality.toFixed(1)}; RGB keyframes {finish.snapshotStageTimingsMs.rgbKeyframes.toFixed(1)}; appearance keyframes {finish.snapshotStageTimingsMs.appearanceKeyframes.toFixed(1)}; synchronized RGB-D {finish.snapshotStageTimingsMs.synchronizedRgbd.toFixed(1)}; retained measurements {finish.snapshotStageTimingsMs.retainedMeasurements.toFixed(1)}. Actual postMessage begin/end/alias epochs {finish.actualMainPostMessageBeginEpochMs ?? 'N/A'} / {finish.actualMainPostMessageEndEpochMs ?? 'N/A'} / {finish.actualMainPostMessageEpochMs ?? 'N/A'}; result receive {finish.mainResultReceiveEpochMs ?? 'N/A'}; worker receive/start/result epochs {finish.workerReceiveEpochMs ?? 'N/A'} / {finish.workerStartEpochMs ?? 'N/A'} / {finish.workerResultPostEpochMs ?? 'N/A'}.</p><p>Finish rAF heartbeat {finish.rafHeartbeatCount}, max gap {finish.rafMaxGapMs.toFixed(1)} ms; long tasks {finish.longTaskCount}, max {finish.longTaskMaxDurationMs.toFixed(1)} ms; PerformanceObserver {finish.performanceObserverSupported ? 'available' : 'unavailable'}.</p><p>Preview mount epoch {previewTiming.mountEpochMs ?? 'N/A'}; first restored-surface paint epoch {previewTiming.firstRestoredSurfacePaintEpochMs ?? 'N/A'}; mount→first paint {previewTiming.mountToFirstPaintMs?.toFixed(1) ?? 'N/A'} ms; Finish click/start→mount {previewTiming.finishStartToMountMs?.toFixed(1) ?? 'N/A'} ms; Finish click/start→first paint {previewTiming.finishStartToFirstPaintMs?.toFixed(1) ?? 'N/A'} ms; Finish completion→mount {previewTiming.finishToMountMs?.toFixed(1) ?? 'N/A'} ms; Finish completion→first paint {previewTiming.finishToFirstPaintMs?.toFixed(1) ?? 'N/A'} ms.</p></>}
      {finish && <p>Snapshot groups ms {finish.snapshotGroupTimingsMs.map((value) => value.toFixed(1)).join(' / ')}; synchronous CPU {finish.snapshotSynchronousCpuMs.toFixed(1)}; yields {finish.snapshotYieldCount}; max uninterrupted snapshot task {finish.maxUninterruptedSnapshotTaskMs.toFixed(1)} ms.</p>}
      {finish && <><p>Finish retained input: {finish.retainedInputFrameCount} frames / {finish.retainedInputSampleCount} samples / {(finish.retainedInputMemoryBytes / 1048576).toFixed(2)} MiB. Eager closed experiments skipped: {finish.closedExperimentalWorkSkipped.join(', ')}.</p>
        <p>Persisted coverage at Finish: {finish.coveragePersistence.cellCountAtFinish} cells (observed/partial/captured {finish.coveragePersistence.observedCellCount}/{finish.coveragePersistence.partialCellCount}/{finish.coveragePersistence.capturedCellCount}); state downgrades/removals before finalization {finish.coveragePersistence.stateDowngradeCount}/{finish.coveragePersistence.cellsRemovedBeforeFinalization}. Presentation-only behavior: captured opacity {finish.coveragePersistence.capturedOverlayOpacity}; dense cache {finish.coveragePersistence.densePresentationCacheLifetimeMs} ms.</p></>}
      {filter && <><p>Confidence filter retained {filter.retainedSamples}/{filter.sourceSamples}; stable {filter.stableSamples}; low-confidence {filter.lowConfidenceSamples}; view-diverse {filter.viewDiverseSamples}; single-view {filter.singleViewSamples}. Removed {filter.samplesRemoved} display candidates.</p>
        <p>Components {filter.connectedComponentCount}; floating low-confidence components excluded {filter.floatingComponentsRejected}; duplicate-sheet candidates {filter.duplicateCandidates}, rejected {filter.duplicateCandidatesRejected}, multi-view confirmed {filter.duplicateCandidatesMultiViewConfirmed}, supported second surface {filter.duplicateCandidatesSupportedSecondSurface}, recess-topology retained {filter.duplicateCandidatesRetainedForRecessTopology}. Mean position/depth/normal variation {filter.meanPositionStdMeters.toFixed(4)} m / {filter.meanDepthStdMeters.toFixed(4)} m / {filter.meanNormalStd.toFixed(3)}. Analysis {filter.componentAnalysisMs.toFixed(1)} ms.</p>
        <p>Repeatability: extent {filter.repeatability.extentMeters.x.toFixed(2)} × {filter.repeatability.extentMeters.y.toFixed(2)} × {filter.repeatability.extentMeters.z.toFixed(2)} m; major components {filter.repeatability.majorComponentCount}; stable {(filter.repeatability.stableSampleRatio*100).toFixed(1)}%; low confidence {(filter.repeatability.lowConfidenceSampleRatio*100).toFixed(1)}%; largest unsupported component {filter.repeatability.largestUnsupportedComponentSamples} samples; ceiling-height proxy {filter.repeatability.ceilingHeightEstimateMeters?.toFixed(2) ?? 'N/A'} m.</p></>}
    </details>}
    {!replayMode && <details><summary>Depth, appearance, memory and walking diagnostics</summary>
      <p>Depth source {source.depthSource?.width ?? '?'} × {source.depthSource?.height ?? '?'}; scale {source.depthSource?.scale ?? '?'} m/raw unit. Tier {q?.tier ?? 0}, four temporal phases. Attempted {q?.attempted ?? 0}; valid {q?.valid ?? 0}. Last processing {q?.processingMs.toFixed(1) ?? '?'} ms.</p>
      <p>Live lightweight matching: last {fusion.createdThisTick ?? 0} new / {fusion.fusedThisTick ?? 0} matched ({fusion.matchRatioPercentage?.toFixed(1) ?? '?'}%). Processed frames {fusion.liveProcessedFrameCount ?? 0}; per-frame budget {fusion.liveMaximumSamplesPerFrame ?? '?'}; decimated samples {fusion.liveInputDecimatedSampleCount ?? 0}. Failed match evidence: distance {fusion.matchDistanceRejectCount ?? 0}; normal {fusion.matchNormalRejectCount ?? 0}; depth layer {fusion.matchDepthLayerRejectCount ?? 0}; empty bucket {fusion.matchBucketMissCount ?? 0}; candidate budget {fusion.matchCandidateBudgetRejectCount ?? 0}. Fusion p50/p95/max {fusion.fusionP50Ms?.toFixed(1) ?? '?'} / {fusion.fusionP95Ms?.toFixed(1) ?? '?'} / {fusion.fusionMaxMs?.toFixed(1) ?? '?'} ms.</p>
      <p>View diversity baseline p50/p90 {fusion.viewBaselineP50Meters?.toFixed(2) ?? '?'} / {fusion.viewBaselineP90Meters?.toFixed(2) ?? '?'} m; angle p50/p90 {fusion.viewAngleP50Degrees?.toFixed(1) ?? '?'} / {fusion.viewAngleP90Degrees?.toFixed(1) ?? '?'}°. View-diverse {fusion.viewDiverseSampleCount ?? 0}; single-view {fusion.singleViewSampleCount ?? 0}.</p>
      <p>Actual normalized-view grid {q?.columns ?? '?'} × {q?.rows ?? '?'}; view-aspect adjusted within the tier sample budget. Smoothed XR frame interval {q?.xrFrameIntervalMs?.toFixed(1) ?? '?'} ms.</p>
      <p>2.5 cm cells; runtime Dense capacity {fusion.capacity}. Active {fusion.activeSampleCount}; stable {fusion.stableSampleCount}; created {fusion.createdSampleCount}; fused {fusion.fusedSampleCount}. Capacity rejects {fusion.capacityRejectedSampleCount ?? 0}; stale unconfirmed reclaimed {fusion.reclaimedSampleCount ?? 0}.</p>
      <p>Appearance source {appearanceSource?.sourceCameraWidth ?? '?'} × {appearanceSource?.sourceCameraHeight ?? '?'} → copy {appearance?.width ?? 0} × {appearance?.height ?? 0}; {appearance?.retainedCount ?? 0}/8 frames; {((appearance?.totalBytes ?? 0) / 1048576).toFixed(2)} MiB. Last total/copy/readback/allocation {appearance?.captureMs.toFixed(1) ?? '?'} / {appearance?.shaderCopyMs.toFixed(1) ?? '?'} / {appearance?.readbackMs.toFixed(1) ?? '?'} / {appearance?.allocationMs.toFixed(1) ?? '?'} ms. Candidate outcomes captured/pressure/motion/duplicate/camera/other: {appearance?.candidateOutcomes.captured ?? 0}/{appearance?.candidateOutcomes.pressureSkipped ?? 0}/{appearance?.candidateOutcomes.motionSkipped ?? 0}/{appearance?.candidateOutcomes.duplicateViewSkipped ?? 0}/{appearance?.candidateOutcomes.cameraUnavailable ?? 0}/{appearance?.candidateOutcomes.other ?? 0}. Mask keyframes unchanged.</p>
      {texture && <><p>Measured-image texture: {texture.textureBatchCount} bounded keyframe batches; {texture.texturedTriangleCount} triangles textured; {texture.fallbackTriangleCount} triangles retain measured vertex RGB; {(texture.rgbBytes / 1048576).toFixed(2)} MiB transferred. Common view rank primary/second/third/later/no-common: {texture.commonPrimaryTriangleCount}/{texture.commonSecondTriangleCount}/{texture.commonThirdTriangleCount}/{texture.commonLaterTriangleCount}/{texture.noCommonViewTriangleCount}.</p>
        <p>Textured source evidence p50/p90: {texture.texelsPerMeter.p50?.toFixed(0) ?? '?'} / {texture.texelsPerMeter.p90?.toFixed(0) ?? '?'} texels/m; incidence {texture.incidence.p50?.toFixed(2) ?? '?'} / {texture.incidence.p90?.toFixed(2) ?? '?'}; distance {texture.distanceMeters.p50?.toFixed(2) ?? '?'} / {texture.distanceMeters.p90?.toFixed(2) ?? '?'} m. Lowest sampled 0.5 m regions: {lowestTextureRegions.map((region) => `${region.region} ${region.texturedTriangles}/${region.totalTriangles} (${region.percentage.toFixed(0)}%)`).join('; ') || 'none'}.</p></>}
      <p>Live RGB {source.liveRgbDimensions?.width ?? '?'} × {source.liveRgbDimensions?.height ?? '?'}. Shared spatial buckets with multiple stored samples: {fusion.multiLayerBucketCount ?? 0} (not a semantic surface count). Last new-observation ratio {((fusion.newGeometryRatio ?? 0) * 100).toFixed(1)}%; fused/repeat ratio {((1 - (fusion.newGeometryRatio ?? 0)) * 100).toFixed(1)}%.</p>
      {stats && <p>Conflicting high-quality appearance observations retaining original RGB: {stats.colorConflictRejects}.</p>}
      {stats && <><p>Color refinement {stats.refinedColors}/{filter?.retainedSamples ?? source.surfels.length} ({(100 * stats.refinedColors / Math.max(1, filter?.retainedSamples ?? source.surfels.length)).toFixed(1)}% of refinement input); visibility rejects {stats.visibilityRejects}; one view {stats.singleView}; multi-view {stats.multipleViews}; {stats.colorMs.toFixed(1)} ms.</p>
        <p>Local noise proxy {(stats.rawNoiseMeters * 1000).toFixed(2)} → {(stats.refinedNoiseMeters * 1000).toFixed(2)} mm. Moved {stats.movedSamples}; displacement mean/p90/p95/max {(stats.meanDisplacementMeters*1000).toFixed(2)} / {(stats.p90DisplacementMeters*1000).toFixed(2)} / {(stats.p95DisplacementMeters*1000).toFixed(2)} / {(stats.maxDisplacementMeters*1000).toFixed(2)} mm; raw retained by displacement safety {stats.retainedRawByDisplacementSafety}; edge samples unchanged {stats.edgeSamplesRetained}; {stats.geometryMs.toFixed(1)} ms. No synthesized vertices or explicit hole filling.</p>
        <p>Triangles {result?.prepared.stats.renderedTriangleCount}; mesh-covered samples {result?.prepared.stats.meshCoveredCanonicalSamples}; measured underlay splats {result?.prepared.stats.measuredUnderlaySplatCount}; visually represented {result?.prepared.stats.visuallyRepresentedSamples}; truly undisplayed {result?.prepared.stats.trulyUndisplayedSamples}; footprint {result?.prepared.stats.visualFootprintKernel}; median/p90 spacing {result?.prepared.stats.medianNearestNeighborSpacingMeters?.toFixed(3)} / {result?.prepared.stats.p90NearestNeighborSpacingMeters?.toFixed(3)} m. Preparation {result?.prepared.stats.renderPreparationMs.toFixed(1)} ms.</p>
        <p>Triangle candidates {result?.prepared.stats.triangleCandidatePairCount}; rejects: edge {result?.prepared.stats.trianglesRejectedByDistance}; normal {result?.prepared.stats.trianglesRejectedByNormal}; depth layer {result?.prepared.stats.trianglesRejectedByDepthLayer}; degenerate {result?.prepared.stats.trianglesRejectedDegenerate}; angular gap {result?.prepared.stats.trianglesRejectedAngularGap}; occupied circumcircle {result?.prepared.stats.trianglesRejectedOccupiedCircumcircle}. Non-participating measured samples / fallback splats {result?.prepared.stats.fallbackSplatCount}. Accepted edge p95/max {result?.prepared.stats.p95AcceptedTriangleEdgeMeters.toFixed(3)} / {result?.prepared.stats.largestAcceptedTriangleEdgeMeters.toFixed(3)} m.</p>
        <p>Numeric memory: live Dense {((fusion.numericMemoryBytes ?? 3660000) / 1048576).toFixed(2)} MiB; retained measurements {((retained?.memoryBytes ?? 0) / 1048576).toFixed(2)}; canonical estimate {((canonical?.numericMemoryBytes ?? 0) / 1048576).toFixed(2)}; derived position/normal {(stats.positionNormalBytes / 1048576).toFixed(2)}; colors {(stats.colorBytes / 1048576).toFixed(2)}; worker scratch {(stats.numericTemporaryBytes / 1048576).toFixed(2)}; mesh {((result?.prepared.stats.memoryBytes ?? 0) / 1048576).toFixed(2)}. JS objects/hash overhead is additional.</p></>}
      <p>Canvas {renderInfo.width} × {renderInfo.height}; DPR {renderInfo.dpr}; {renderInfo.fps} FPS; {renderInfo.drawCalls} draw calls. Browser render proxy: resource restore/setup {renderInfo.restoreSetupMs?.toFixed(1) ?? 'N/A'} ms; first renderer.render after each prepared resource {renderInfo.firstRenderCallMs?.toFixed(1) ?? 'N/A'} ms; rolling steady renderer.render {renderInfo.rollingRenderCallMs?.toFixed(2) ?? 'N/A'} ms. These timings are browser proxies for setup/compile/draw; exact GPU upload is not measured.</p>
      <p>Position/normal/color memory figures are packed-equivalent estimates; derived samples are JS objects. Browser peak memory and GPU allocations require device profiling. Snapshot cloning temporarily duplicates raw samples/keyframes; only one preview is mounted at a time.</p>
      <p>Walked {q?.distanceWalkedMeters.toFixed(2) ?? '0'} m; trajectory {q?.trajectory.length ?? 0}/1024 poses; stationary ticks skipped {q?.skippedStationaryTicks ?? 0}. Walking distance is tracked pose-path length, not drift-corrected ground truth.</p>
    </details>}
  </section>
}
